### ISSUE TITLE
Class not found after migrating to 1.1.0 - missing OAuth2DeviceAuthorizationResponseHttpMessageConverter

### ISSUE THREAD

**Issue by wheredoipressnow** [spring-projects/spring-authorization-server#1217]
After bumping version from 1.0.1 to 1.1.0 the project fails to start up with message
`java.lang.NoClassDefFoundError: org/springframework/security/oauth2/core/http/converter/OAuth2DeviceAuthorizationResponseHttpMessageConverter
`

@sjohnr I found the article on Stackoverflow describing the same problem
[https://stackoverflow.com/questions/75850924/spring-authorization-server-doesnt-run](https://stackoverflow.com/questions/75850924/spring-authorization-server-doesnt-run)

**Comment by herodotus-cloud** [comment]
Spring Authorization Server 1.1.0 depends on the latest version of Spring Security 6.1.0。

**Comment by wheredoipressnow** [comment]
Expectation is that it works with latest Spring Boot Parent as does the previous version. The migration guide does not mention any extra steps to configure additional dependencies.

```
    <parent>
        <groupId>org.springframework.boot</groupId>
        <artifactId>spring-boot-starter-parent</artifactId>
        <version>3.0.6</version>
        <relativePath/>
    </parent>
```

**Comment by jgrandja** [comment]
@wheredoipressnow 

> Expectation is that it works with latest Spring Boot Parent as does the previous version

This is not correct. Spring Authorization Server is not dependent on Spring Boot but it is dependent on Spring Security.
Spring Authorization Server `1.1.0` depends on Spring Security `6.1.0`. See [gradle.properties](https://github.com/spring-projects/spring-authorization-server/blob/main/gradle.properties#L6).

The issue you are likely having is because you are using an older version of Spring Boot. The [default-authorizationserver](https://github.com/spring-projects/spring-authorization-server/blob/main/samples/default-authorizationserver/samples-default-authorizationserver.gradle#L2) sample is using `3.1.0-RC1`.

> I found the article on Stackoverflow describing the same problem

If you look at the comments in the post you will see it's related to the Spring Security version you are using.
